### ISSUE TITLE
SRN: Path of the storage location

### ISSUE THREAD

**Issue by Sateetje** [proximax-storage/sirius-storage-mainnet-onboarding#10]
What is the default path of the storage location when using Docker?

Where can I change the default path?

**Comment by shinneng** [comment]
```
version: "3.6"
services:
  replicator:
    image: proximax/dfms-replicator:v0.8.1
    ports:
      - 6466:6466
      - 64666:64666
    volumes:
      - ./:/root/.dfms-replicator:rw
    restart: on-failure:3
    entrypoint: /usr/bin/dfms-replicator
```
the docker-compose mounts the current path as per line ` - ./:/root/.dfms-replicator:rw`.  

e.g. if you want to mount `/mnt/replicator/`, then you can change as following `- /mnt/replicator/:/root/.dfms-replicator:rw`
