### ISSUE TITLE
Docker-compose

### ISSUE THREAD

**Issue by Sateetje** [proximax-storage/sirius-storage-mainnet-onboarding#8]
Is it possible to use docker-compose instead of this bash script?

![afbeelding](https://user-images.githubusercontent.com/16215404/99970655-6e15c280-2d9c-11eb-8be8-689378a05a50.png)

**Comment by shinneng** [comment]
Will this be a good feature?


docker-compose.yml:
```
version: "3.6"
services:
  director:
    image: proximax/dfms-client:v0.8.1
    ports:
      - 6366:6366
      - 63666:63666
    volumes:
      - ./:/root/.dfms-client:rw
    restart: on-failure:3
    entrypoint: /usr/bin/dfms-client
    command: "-k PRIVATE_KEY"
```

To use the `dfms-client` command line, you can create alias:
```
alias dfms-client="docker-compose -f DOCKER_COMPOSE_PATH exec director dfms-client"
# e.g. if docker-compose.yml is located in /home/user/sirius-storage-mainnet-onboarding/director/docker-compose.yml then
# alias dfms-client="docker-compose -f /home/user/sirius-storage-mainnet-onboarding/director/docker-compose.yml exec director dfms-client"

# test alias
dfms-client version
dfms-client net id
```
